### ISSUE TITLE
should /notes/{id} throw an error if the noteid doesnt exist?

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/nlp-sandbox-data-node-i2b2-2014#60]
Currently an empty array is returned, should an error be thrown instead?

**Comment by tschaffter** [comment]
The schema defines correctly that a 404 status code must be returned.
https://sage-bionetworks.github.io/nlp-sandbox-schemas/data-node/edge/docs/#operation/notes.read

## Update

I'm preparing the [release 0.1.2](https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/pull/39) for the nlp-sandbox-schemas that now specify that a JSON object must be returned when a note is not found.

![image](https://user-images.githubusercontent.com/3056480/96073244-efec0500-0e5a-11eb-909b-bde7c99aba94.png)

**Comment by tschaffter** [comment]
Depends on https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/pull/39.

**Comment by gkowalski** [comment]
picky picky ;-)

**Comment by tschaffter** [comment]
An error object with the following properties is now returned when the specified note is not found:

![image](https://user-images.githubusercontent.com/3056480/96346701-158f2f00-1052-11eb-84dc-456e8be27233.png)
